name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm ci

    - name: Install Linux dependencies
      run: sudo apt-get update && sudo apt-get install -y libx11-xcb1 libasound2 libnss3 libxss1 libxrandr2 libgtk-3-0 libxshmfence1 libgbm1 xvfb

    - name: Run tests
      run: |
        export DISPLAY=':99.0'
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        npm run test
